"""REW EQ text file parser — converts REW text and HTTP API data to CanonicalFilter lists.

Handles both the simple 'Equaliser: Parametric EQ' format (generated by REWGenerator)
and the full REW "Filter Settings file" export format with preamble, various filter
types, and duplicate measurement sections. Also accepts REW-import-compatible files
that have no 'Equaliser:' header at all (e.g. AutoEQ, spinorama.org exports), and
their "LSC"/"HSC" shelf-filter tokens.
"""

from __future__ import annotations

import re
from pathlib import Path

from src.logging.setup import rew_api_logger as logger
from src.models.canonical import CanonicalFilter
from src.models.constants import FREQ_MAX, FREQ_MIN
from src.models.errors import ParseError, ValidationError
from src.translator._warnings import FilterRow, SkippedBand, ValidationWarning

# ---------------------------------------------------------------------------
# Filter line regex — matches the "Filter  N:" prefix and captures state
# ---------------------------------------------------------------------------
_FILTER_PREFIX_RE = re.compile(
    r"^Filter\s+(\d+):\s+(ON|OFF)\s+(.*)$"
)

# ---------------------------------------------------------------------------
# Individual filter body patterns (after stripping state prefix)
# ---------------------------------------------------------------------------

# PK Fc <freq> Hz Gain <gain> dB Q <q>
_PK_RE = re.compile(
    r"^PK\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HP Q Fc <freq> Hz Q <q>
_HP_Q_RE = re.compile(
    r"^HP\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Q\s+([\d.]+)\s*$"
)

# LP Q Fc <freq> Hz Q <q>
_LP_Q_RE = re.compile(
    r"^LP\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Q\s+([\d.]+)\s*$"
)

# LS Q Fc <freq> Hz Gain <gain> dB Q <q>
_LS_Q_RE = re.compile(
    r"^LS\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HS Q Fc <freq> Hz Gain <gain> dB Q <q>
_HS_Q_RE = re.compile(
    r"^HS\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# ASSUMPTION: LSC/HSC (AutoEQ / Equalizer APO's Q-parametrized shelf tokens)
# are treated as identical to REW's own "LS Q"/"HS Q" -- same canonical
# LS/HS type, Gain and Q taken literally. Supported by REW's/Equalizer
# APO's own documentation and AutoEQ's own bug report (GitHub issue #586:
# a user's measured curve only matched AutoEQ's documented target after
# relabeling identical Fc/Gain/Q filters from LS/HS to LSC/HSC), not by
# hardware testing against a real WiiM device's shelf filter. See
# docs/corrections.md, 2026-08-10.

# LSC Fc <freq> Hz Gain <gain> dB Q <q> — AutoEQ / Equalizer APO low-shelf
# token (fully Q-specified, equivalent to REW's "LS Q" variant)
_LSC_RE = re.compile(
    r"^LSC\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HSC Fc <freq> Hz Gain <gain> dB Q <q> — AutoEQ / Equalizer APO high-shelf
# token (fully Q-specified, equivalent to REW's "HS Q" variant)
_HSC_RE = re.compile(
    r"^HSC\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HP Fc <freq> Hz (Butterworth, no Q specified)
_HP_BW_RE = re.compile(
    r"^HP\s+Fc\s+([\d.]+)\s+Hz\s*$"
)

# LP Fc <freq> Hz (Butterworth, no Q specified)
_LP_BW_RE = re.compile(
    r"^LP\s+Fc\s+([\d.]+)\s+Hz\s*$"
)

# LS Fc <freq> Hz Gain <gain> dB (bare shelf — REW's slope parameter S, no Q;
# used only to detect+skip this unsupported variant, see _SKIP_TYPES below)
_LS_FIXED_RE = re.compile(
    r"^LS\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s*$"
)

# HS Fc <freq> Hz Gain <gain> dB (bare shelf — REW's slope parameter S, no Q;
# used only to detect+skip this unsupported variant, see _SKIP_TYPES below)
_HS_FIXED_RE = re.compile(
    r"^HS\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s*$"
)

# None (empty/disabled band)
_NONE_RE = re.compile(r"^None\s*$")

# Legacy format: <type> Fc <freq> Hz Gain <gain> dB Q <q>  (for backward compat)
_LEGACY_FULL_RE = re.compile(
    r"^(\w+)\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-+\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# REW's documented fixed Q for bare LP/HP (12 dB/octave Butterworth alignment)
_BUTTERWORTH_Q = 0.7071

# Surfaced to the user (Review table) whenever a bare LP/HP gets this default
# applied, since unlike LP Q/HP Q (a direct, lossless match) this substitutes
# a value the source file never specified.
_BUTTERWORTH_Q_NOTE = (
    "REW's bare {0} has no explicit Q; using REW's documented fixed "
    f"Q={_BUTTERWORTH_Q:.4f} (12 dB/octave Butterworth alignment)."
)

# ---------------------------------------------------------------------------
# Unified type map and skip types (shared by text file parser and API parser)
# ---------------------------------------------------------------------------

# All known filter type tokens -> Canonical filter type.
#
# "LS"/"HS" stay mapped here (rather than moving to _SKIP_TYPES) purely so the
# *legacy round-trip* format this app's own REWGenerator writes — bare "LS"/
# "HS" token with an explicit trailing "Q <value>", matched by
# _LEGACY_FULL_RE — keeps working. Real REW exports never put a Q on a bare
# LS/HS line (see _SKIP_TYPES below), so there is no ambiguity in practice.
_TYPE_MAP: dict[str, str] = {
    "PK": "PEAK",
    "LS": "LS",
    "HS": "HS",
    "LP": "LP",
    "HP": "HP",
    "LS Q": "LS",
    "HS Q": "HS",
    "LP Q": "LP",
    "HP Q": "HP",
}

# Filter types that should be skipped (not translatable to WiiM PEQ).
#
# "LS"/"HS" (bare), "LS 6dB"/"HS 6dB", and "LS 12dB"/"HS 12dB" use REW's shelf
# *slope* parameter S (0.9 / 0.5 / 1.0 respectively per REW's documentation),
# not a Q. WiiM's LV2 EqNp plugin exposes only a single "Q factor" parameter
# for shelf bands (docs/wiim_api_notes.md) with no separate slope input, and
# there is no hardware-validated S->Q conversion — see docs/corrections.md.
# "LP1"/"HP1" are 1st-order (6dB/octave) filters, which have no Q at all.
_SKIP_TYPES: set[str] = {
    "None",       # Empty/disabled slot
    "Modal",      # Modal decay target
    "All pass",   # Phase-only filter
    "L-T",        # Linkwitz Transform
    "Notch",      # REW notch implies >60 dB attenuation; WiiM caps gain at -12 dB
    "Notch Q",    # Same as above, explicit-Q variant
    "LS",         # Shelf-slope (S=0.9) shelf, no Q equivalent confirmed
    "HS",         # Shelf-slope (S=0.9) shelf, no Q equivalent confirmed
    "LS 6dB",     # Shelf-slope (S=0.5) shelf, no Q equivalent confirmed
    "HS 6dB",     # Shelf-slope (S=0.5) shelf, no Q equivalent confirmed
    "LS 12dB",    # Shelf-slope (S=1.0) shelf, no Q equivalent confirmed
    "HS 12dB",    # Shelf-slope (S=1.0) shelf, no Q equivalent confirmed
    "LP1",        # 1st-order low-pass, no Q
    "HP1",        # 1st-order high-pass, no Q
}


def _validate_frequency(
    freq: float, *, line_number: int | None = None, band_index: int | None = None
) -> None:
    """Raise ValidationError if frequency is outside 10-22000 Hz."""
    if not (FREQ_MIN <= freq <= FREQ_MAX):
        msg = f"Frequency {freq} Hz is outside valid range {FREQ_MIN:g}-{FREQ_MAX:g} Hz"
        if line_number is not None:
            msg = f"Line {line_number}: {msg}"
        elif band_index is not None:
            msg = f"Band {band_index}: {msg}"
        raise ValidationError(msg)


def _classify_filter_type(type_token: str, index: int) -> str | None:
    """Classify a filter type token into a canonical type string.

    Returns the canonical type ("PEAK", "LS", "HS", "LP", "HP") if supported,
    or None if the filter should be skipped.

    Logs a warning for unknown types.
    """
    if type_token in _SKIP_TYPES:
        logger.debug("Filter %d: skipping type '%s' (not translatable)", index, type_token)
        return None
    if type_token in _TYPE_MAP:
        return _TYPE_MAP[type_token]
    # Unknown type - skip with warning
    logger.warning("Filter %d: unknown type '%s' - skipping", index, type_token)
    return None


def _is_unsupported_filter(body: str) -> str | None:
    """Check if the filter body starts with an unsupported type token.

    Returns the unsupported type name if found, None otherwise.
    Uses _SKIP_TYPES for known skip types, plus regex for text-format variants.
    """
    # Check explicit skip types by prefix (exclude "None" — handled by _NONE_RE;
    # "All pass" — handled by regex below so a hyphenated "All-pass" input is
    # also recognized and normalized to the space form;
    # "Notch"/"Notch Q" — handled by regex below so the more specific
    # "Notch Q" label isn't shadowed by a "Notch" prefix match; "LS"/"HS" —
    # handled by regex below, anchored to "Fc" right after the type token, so
    # a bare-prefix match here doesn't shadow the supported "LS Q"/"HS Q"
    # variants or this app's own legacy round-trip format, "LS ... Q <value>")
    for utype in _SKIP_TYPES:
        if utype in ("None", "All pass", "Notch", "Notch Q", "LS", "HS"):
            continue
        if body.startswith(utype):
            return utype

    # Check "Notch Q" variant (multi-word before single "Notch" check) — REW
    # notches imply >60 dB attenuation, which WiiM cannot reproduce (gain
    # capped at -12 dB), so both variants are always unsupported.
    notch_q = re.match(r"^Notch\s+Q\b", body)
    if notch_q:
        return "Notch Q"

    # Check single "Notch"
    notch = re.match(r"^Notch\b", body)
    if notch:
        return "Notch"

    # Check "All pass" or "All-pass" (REW's own text export always uses the
    # space form; the hyphen is tolerated on input but normalized to "All
    # pass" on output, matching the live-API path's raw type token exactly)
    allpass = re.match(r"^All[\s-]?pass\b", body)
    if allpass:
        return "All pass"

    # Check bare "LS"/"HS" (REW's shelf-slope "S"-parameterized shelf, with no
    # Q field at all — see _SKIP_TYPES). Anchored to require "Fc" immediately
    # after the type token, so "LS Q ..." (explicit Q) and this app's own
    # legacy round-trip format (bare token + trailing "Q <value>") don't match.
    if _LS_FIXED_RE.match(body):
        return "LS"
    if _HS_FIXED_RE.match(body):
        return "HS"

    return None


def _parse_filter_body(
    body: str, *, line_number: int
) -> tuple[CanonicalFilter | None, ValidationWarning | None, str | None]:
    """Parse the body of a filter line (everything after ON/OFF prefix).

    Returns (CanonicalFilter, None, note) on success, or (None, ValidationWarning,
    None) for unsupported types that should be skipped. `note` is non-None only
    when a value had to be substituted for one REW didn't specify (currently:
    the fixed Butterworth Q applied to a bare LP/HP) — surfaced to the user as
    a conversion note, distinct from an outright skip.

    Raises ParseError for malformed lines.
    """
    # --- None (empty band) ---
    if _NONE_RE.match(body):
        return (
            CanonicalFilter(type="OFF", frequency_hz=1000.0, gain_db=0.0, q=1.0),
            None,
            None,
        )

    # --- Check for unsupported types before trying supported patterns ---
    unsupported = _is_unsupported_filter(body)
    if unsupported:
        warning = ValidationWarning(
            field="filter_type",
            message=f"Unsupported filter type '{unsupported}' at line {line_number}, skipping",
            original_value=unsupported,
            clamped_value=None,
        )
        return (None, warning, None)

    # --- PK (Peaking/Parametric) ---
    m = _PK_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="PEAK", frequency_hz=freq, gain_db=gain, q=q),
            None,
            None,
        )

    # --- HP Q (High-pass with explicit Q) ---
    m = _HP_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        q = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="HP", frequency_hz=freq, gain_db=0.0, q=q),
            None,
            None,
        )

    # --- LP Q (Low-pass with explicit Q) ---
    m = _LP_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        q = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="LP", frequency_hz=freq, gain_db=0.0, q=q),
            None,
            None,
        )

    # --- LS Q (Low-shelf with explicit Q) ---
    m = _LS_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="LS", frequency_hz=freq, gain_db=gain, q=q),
            None,
            None,
        )

    # --- HS Q (High-shelf with explicit Q) ---
    m = _HS_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="HS", frequency_hz=freq, gain_db=gain, q=q),
            None,
            None,
        )

    # --- LSC (AutoEQ / Equalizer APO low-shelf, explicit Q) ---
    m = _LSC_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="LS", frequency_hz=freq, gain_db=gain, q=q),
            None,
            None,
        )

    # --- HSC (AutoEQ / Equalizer APO high-shelf, explicit Q) ---
    m = _HSC_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="HS", frequency_hz=freq, gain_db=gain, q=q),
            None,
            None,
        )

    # --- HP Butterworth (no Q specified) ---
    m = _HP_BW_RE.match(body)
    if m:
        freq = float(m.group(1))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="HP", frequency_hz=freq, gain_db=0.0, q=_BUTTERWORTH_Q
            ),
            None,
            _BUTTERWORTH_Q_NOTE.format("HP"),
        )

    # --- LP Butterworth (no Q specified) ---
    m = _LP_BW_RE.match(body)
    if m:
        freq = float(m.group(1))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="LP", frequency_hz=freq, gain_db=0.0, q=_BUTTERWORTH_Q
            ),
            None,
            _BUTTERWORTH_Q_NOTE.format("LP"),
        )

    # --- Legacy full format: <type> Fc <freq> Hz Gain <gain> dB Q <q> ---
    # This catches LP/HS/LS/HP with Gain+Q in the format generated by REWGenerator
    m = _LEGACY_FULL_RE.match(body)
    if m:
        type_token = m.group(1)
        freq = float(m.group(2))
        gain = float(m.group(3))
        q = float(m.group(4))

        if type_token not in _TYPE_MAP:
            # Unknown type in legacy format — could be unsupported
            warning = ValidationWarning(
                field="filter_type",
                message=(
                    f"Unsupported filter type '{type_token}' at line {line_number}, skipping"
                ),
                original_value=type_token,
                clamped_value=None,
            )
            return (None, warning, None)

        _validate_frequency(freq, line_number=line_number)
        canonical_type = _TYPE_MAP[type_token]
        return (
            CanonicalFilter(
                type=canonical_type,  # type: ignore[arg-type]
                frequency_hz=freq,
                gain_db=gain,
                q=q,
            ),
            None,
            None,
        )

    # If we get here, the body didn't match any known pattern
    raise ParseError(
        f"Malformed filter line: '{body}'",
        line_number=line_number,
    )


class REWParser:
    """Parses REW EQ text files and REW HTTP API FilterSetting objects into CanonicalFilters."""

    def parse_file(self, path: Path) -> list[CanonicalFilter]:
        """Parse a REW EQ text file.

        Handles both the simple format (first line 'Equaliser: Parametric EQ')
        and the full REW "Filter Settings file" export format with preamble.

        Raises ParseError on malformed lines (with line number in message).
        Raises ValidationError for out-of-range frequency.
        Emits ValidationWarning for unsupported filter types (skips those bands).

        Returns:
            List of CanonicalFilter objects. Access warnings via
            parse_file_with_warnings() for the full result.
        """
        result, _warnings = self.parse_file_with_warnings(path)
        return result

    def parse_file_with_warnings(
        self, path: Path
    ) -> tuple[list[CanonicalFilter], list[ValidationWarning]]:
        """Parse a REW EQ text file, returning both filters and warnings.

        Raises ParseError on malformed lines (with line number in message).
        Raises ValidationError for out-of-range frequency.

        Returns:
            Tuple of (filters, warnings).
        """
        filters, warnings, _rows, _notes = self._parse_file_full(path)
        return filters, warnings

    def parse_file_with_rows(
        self, path: Path
    ) -> tuple[
        list[CanonicalFilter], list[ValidationWarning], list[FilterRow], dict[int, list[str]]
    ]:
        """Parse a REW EQ text file, also returning display rows in original order.

        Raises ParseError on malformed lines (with line number in message).
        Raises ValidationError for out-of-range frequency.

        Returns:
            Tuple of (filters, warnings, rows, conversion_notes). `rows` preserves
            the original band order, interleaving SkippedBand placeholders for
            unsupported types at the position they occupied in the source file.
            `conversion_notes` maps a band's 0-based index in `filters` to a list
            of notes about values REW didn't specify and had to be substituted
            (currently: the fixed Q applied to a bare, Q-less LP/HP) — distinct
            from an outright skip, since the band is still fully usable.
        """
        return self._parse_file_full(path)

    def _parse_file_full(
        self, path: Path
    ) -> tuple[
        list[CanonicalFilter], list[ValidationWarning], list[FilterRow], dict[int, list[str]]
    ]:
        """Shared implementation backing parse_file_with_warnings/_rows."""
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()

        if not lines:
            raise ParseError(
                "Expected 'Equaliser:' header line but file is empty",
                line_number=1,
            )

        # Find the Equaliser: header line (skip preamble). Real REW exports
        # always have this line, but other REW-import-compatible tools (e.g.
        # AutoEQ, spinorama.org) export "Filter N: ON ..." lines directly
        # with no Equaliser: header — treat the header as optional and scan
        # from the top of the file when it's absent.
        equaliser_line_idx: int | None = None
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("Equaliser:"):
                equaliser_line_idx = i
                break

        start_idx = equaliser_line_idx + 1 if equaliser_line_idx is not None else 0

        # Parse filter lines after the equaliser header (or from the top of
        # the file, if there is no header)
        filters: list[CanonicalFilter] = []
        warnings: list[ValidationWarning] = []
        rows: list[FilterRow] = []
        conversion_notes: dict[int, list[str]] = {}
        seen_filter_numbers: set[int] = set()
        found_filter_line = False

        for line_idx in range(start_idx, len(lines)):
            line = lines[line_idx]
            stripped = line.strip()
            line_number = line_idx + 1  # 1-based for error messages

            if not stripped:
                continue  # Skip blank lines

            # Try to match a filter line
            prefix_match = _FILTER_PREFIX_RE.match(stripped)
            if prefix_match is None:
                # Non-filter lines after the header (e.g. "L+R+Sub (closed)",
                # "No measurement") are silently skipped
                continue

            found_filter_line = True
            filter_num = int(prefix_match.group(1))
            state = prefix_match.group(2)  # ON or OFF
            body = prefix_match.group(3).strip()

            # Detect duplicate filter section (REW appends extra measurement filters)
            if filter_num in seen_filter_numbers:
                break  # Stop parsing — duplicate section starts here
            seen_filter_numbers.add(filter_num)

            # Parse the filter body
            result, warning, note = _parse_filter_body(body, line_number=line_number)

            if warning is not None:
                warnings.append(warning)
                rows.append(
                    SkippedBand(
                        original_type=str(warning.original_value),
                        reason=warning.message,
                    )
                )
                continue  # Skip unsupported filter types

            if result is None:  # pragma: no cover
                continue

            # Apply OFF state: if state is OFF, override the type to OFF
            if state == "OFF":
                result = CanonicalFilter(
                    type="OFF",
                    frequency_hz=result.frequency_hz,
                    gain_db=result.gain_db,
                    q=result.q,
                )

            if note is not None:
                conversion_notes.setdefault(len(filters), []).append(note)

            filters.append(result)
            rows.append(result)

        if equaliser_line_idx is None and not found_filter_line:
            raise ParseError(
                "Expected an 'Equaliser:' header line or 'Filter N: ON/OFF ...' "
                "lines, found neither in file",
                line_number=1,
            )

        return (filters, warnings, rows, conversion_notes)

    def parse_filter_settings(
        self, filter_settings: list[dict[str, object]]
    ) -> list[CanonicalFilter]:
        """Parse REW HTTP API FilterSetting objects into CanonicalFilters.

        Each FilterSetting has: enabled (bool), type (str), frequency (float),
        gaindB (float), q (float). Some filters have no frequency/gain (e.g. None type).

        "None" (empty slot) always becomes an explicit OFF band. Other
        unsupported filter types (Modal, All pass, L-T, Notch/Notch Q,
        LP1/HP1, and the shelf-slope LS/HS/LS 6dB/HS 6dB/LS 12dB/HS 12dB
        variants — see _SKIP_TYPES) are skipped with a logged warning rather
        than raising a hard error.

        Raises:
            ValidationError: A band's frequency is outside 10-22000 Hz.
        """
        filters, _rows, _notes = self.parse_filter_settings_with_rows(filter_settings)
        return filters

    def parse_filter_settings_with_rows(
        self, filter_settings: list[dict[str, object]]
    ) -> tuple[list[CanonicalFilter], list[FilterRow], dict[int, list[str]]]:
        """Parse REW HTTP API FilterSetting objects, also returning display rows.

        Returns:
            Tuple of (filters, rows, conversion_notes). `rows` preserves the
            original band order, interleaving SkippedBand placeholders for
            unsupported types. "None" (empty) slots become an explicit OFF band
            in both, matching the text-file import path's _NONE_RE handling
            exactly. `conversion_notes` maps a band's 0-based index in `filters`
            to a list of notes about values REW's API omitted and had to be
            substituted (currently: the fixed Q applied to a bare, Q-less LP/HP).

        Raises:
            ValidationError: A band's frequency is outside 10-22000 Hz.
        """
        filters: list[CanonicalFilter] = []
        rows: list[FilterRow] = []
        conversion_notes: dict[int, list[str]] = {}

        for i, setting in enumerate(filter_settings):
            enabled = setting.get("enabled", setting.get("on", True))
            type_token = str(setting.get("type", ""))

            # "None" (empty slot) always becomes an explicit OFF band -- never
            # omitted, never treated as "unsupported" -- regardless of
            # `enabled`, matching _NONE_RE's handling in the text-file path.
            if type_token == "None":  # noqa: S105 -- REW's empty-slot type, not a secret
                off_result = CanonicalFilter(
                    type="OFF", frequency_hz=1000.0, gain_db=0.0, q=1.0
                )
                filters.append(off_result)
                rows.append(off_result)
                continue

            canonical_type = _classify_filter_type(type_token, i + 1)
            if canonical_type is None:
                rows.append(
                    SkippedBand(
                        original_type=type_token,
                        reason=(
                            f"Unsupported filter type '{type_token}' - "
                            "no WiiM equivalent"
                        ),
                    )
                )
                continue

            # Parse numeric fields (REW uses "gaindB" or "gain", "frequency" or "freq")
            freq = float(
                setting.get("frequency", setting.get("freq", 1000.0))  # type: ignore[arg-type]
            )
            _validate_frequency(freq, band_index=i + 1)
            gain = float(
                setting.get("gaindB", setting.get("gain", 0.0))  # type: ignore[arg-type]
            )
            # REW's live API omits "q" entirely for LP/HP when no explicit Q was
            # set (confirmed against real REW API output) — use REW's own
            # documented fixed Q for those two types rather than an arbitrary
            # 1.0, matching the text-file import path's behavior exactly.
            q_raw = setting.get("q")
            if q_raw is None:
                q = _BUTTERWORTH_Q if canonical_type in ("LP", "HP") else 1.0
                if canonical_type in ("LP", "HP"):
                    conversion_notes.setdefault(len(filters), []).append(
                        _BUTTERWORTH_Q_NOTE.format(canonical_type)
                    )
            else:
                q = float(q_raw)  # type: ignore[arg-type]

            # Determine canonical type
            if not enabled:
                canonical_type = "OFF"

            result = CanonicalFilter(
                type=canonical_type,  # type: ignore[arg-type]
                frequency_hz=freq,
                gain_db=gain,
                q=q,
            )
            filters.append(result)
            rows.append(result)

        return filters, rows, conversion_notes
