"""REW EQ text file parser — converts REW text and HTTP API data to CanonicalFilter lists.

Handles both the simple 'Equaliser: Parametric EQ' format (generated by REWGenerator)
and the full REW "Filter Settings file" export format with preamble, various filter
types, and duplicate measurement sections.
"""

from __future__ import annotations

import re
from pathlib import Path

from src.models.canonical import CanonicalFilter
from src.models.errors import ParseError, ValidationError
from src.translator._warnings import ValidationWarning

# ---------------------------------------------------------------------------
# Filter line regex — matches the "Filter  N:" prefix and captures state
# ---------------------------------------------------------------------------
_FILTER_PREFIX_RE = re.compile(
    r"^Filter\s+(\d+):\s+(ON|OFF)\s+(.*)$"
)

# ---------------------------------------------------------------------------
# Individual filter body patterns (after stripping state prefix)
# ---------------------------------------------------------------------------

# PK Fc <freq> Hz Gain <gain> dB Q <q>
_PK_RE = re.compile(
    r"^PK\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HP Q Fc <freq> Hz Q <q>
_HP_Q_RE = re.compile(
    r"^HP\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Q\s+([\d.]+)\s*$"
)

# LP Q Fc <freq> Hz Q <q>
_LP_Q_RE = re.compile(
    r"^LP\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Q\s+([\d.]+)\s*$"
)

# LS Q Fc <freq> Hz Gain <gain> dB Q <q>
_LS_Q_RE = re.compile(
    r"^LS\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HS Q Fc <freq> Hz Gain <gain> dB Q <q>
_HS_Q_RE = re.compile(
    r"^HS\s+Q\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# HP Fc <freq> Hz (Butterworth, no Q specified)
_HP_BW_RE = re.compile(
    r"^HP\s+Fc\s+([\d.]+)\s+Hz\s*$"
)

# LP Fc <freq> Hz (Butterworth, no Q specified)
_LP_BW_RE = re.compile(
    r"^LP\s+Fc\s+([\d.]+)\s+Hz\s*$"
)

# LS Fc <freq> Hz Gain <gain> dB (fixed slope, no Q)
_LS_FIXED_RE = re.compile(
    r"^LS\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s*$"
)

# HS Fc <freq> Hz Gain <gain> dB (fixed slope, no Q)
_HS_FIXED_RE = re.compile(
    r"^HS\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s*$"
)

# LS 12dB Fc <freq> Hz Gain <gain> dB
_LS_12DB_RE = re.compile(
    r"^LS\s+12dB\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s*$"
)

# HS 12dB Fc <freq> Hz Gain <gain> dB
_HS_12DB_RE = re.compile(
    r"^HS\s+12dB\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s*$"
)

# None (empty/disabled band)
_NONE_RE = re.compile(r"^None\s*$")

# Legacy format: <type> Fc <freq> Hz Gain <gain> dB Q <q>  (for backward compat)
_LEGACY_FULL_RE = re.compile(
    r"^(\w+)\s+Fc\s+([\d.]+)\s+Hz\s+Gain\s+([-\d.]+)\s+dB\s+Q\s+([\d.]+)\s*$"
)

# Default Butterworth Q value
_BUTTERWORTH_Q = 0.707

# REW text type token -> Canonical filter type
_TYPE_MAP: dict[str, str] = {
    "PK": "PEAK",
    "LS": "LS",
    "HS": "HS",
    "LP": "LP",
    "HP": "HP",
}

# Unsupported filter types that should emit a warning and be skipped
_UNSUPPORTED_TYPES: set[str] = {
    "Modal", "LP1", "HP1", "Notch", "L-T",
}

# REW HTTP API type field -> Canonical filter type (same mapping)
_API_TYPE_MAP: dict[str, str] = {
    "PK": "PEAK",
    "LS": "LS",
    "HS": "HS",
    "LP": "LP",
    "HP": "HP",
}


def _validate_frequency(freq: float, *, line_number: int | None = None) -> None:
    """Raise ValidationError if frequency is outside 10-22000 Hz."""
    if not (10.0 <= freq <= 22000.0):
        msg = f"Frequency {freq} Hz is outside valid range 10-22000 Hz"
        if line_number is not None:
            msg = f"Line {line_number}: {msg}"
        raise ValidationError(msg)


def _is_unsupported_filter(body: str) -> str | None:
    """Check if the filter body starts with an unsupported type token.

    Returns the unsupported type name if found, None otherwise.
    """
    # Check explicit unsupported types
    for utype in _UNSUPPORTED_TYPES:
        if body.startswith(utype):
            return utype

    # Check patterns like "LS 6dB", "HS 6dB" (unsupported slope variants)
    ls_6db = re.match(r"^LS\s+6dB\b", body)
    if ls_6db:
        return "LS 6dB"
    hs_6db = re.match(r"^HS\s+6dB\b", body)
    if hs_6db:
        return "HS 6dB"

    # Check "Notch Q" variant
    notch_q = re.match(r"^Notch\s+Q\b", body)
    if notch_q:
        return "Notch Q"

    # Check "All pass" or "All-pass"
    allpass = re.match(r"^All[\s-]?pass\b", body)
    if allpass:
        return "All-pass"

    return None


def _parse_filter_body(
    body: str, *, line_number: int
) -> tuple[CanonicalFilter | None, ValidationWarning | None]:
    """Parse the body of a filter line (everything after ON/OFF prefix).

    Returns (CanonicalFilter, None) on success, or (None, ValidationWarning) for
    unsupported types that should be skipped.

    Raises ParseError for malformed lines.
    """
    # --- None (empty band) ---
    if _NONE_RE.match(body):
        return (
            CanonicalFilter(type="OFF", frequency_hz=1000.0, gain_db=0.0, q=1.0),
            None,
        )

    # --- Check for unsupported types before trying supported patterns ---
    unsupported = _is_unsupported_filter(body)
    if unsupported:
        warning = ValidationWarning(
            field="filter_type",
            message=f"Unsupported filter type '{unsupported}' at line {line_number}, skipping",
            original_value=unsupported,
            clamped_value=None,
        )
        return (None, warning)

    # --- PK (Peaking/Parametric) ---
    m = _PK_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="PEAK", frequency_hz=freq, gain_db=gain, q=q),
            None,
        )

    # --- HP Q (High-pass with explicit Q) ---
    m = _HP_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        q = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="HP", frequency_hz=freq, gain_db=0.0, q=q),
            None,
        )

    # --- LP Q (Low-pass with explicit Q) ---
    m = _LP_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        q = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="LP", frequency_hz=freq, gain_db=0.0, q=q),
            None,
        )

    # --- LS Q (Low-shelf with explicit Q) ---
    m = _LS_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="LS", frequency_hz=freq, gain_db=gain, q=q),
            None,
        )

    # --- HS Q (High-shelf with explicit Q) ---
    m = _HS_Q_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        q = float(m.group(3))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(type="HS", frequency_hz=freq, gain_db=gain, q=q),
            None,
        )

    # --- LS 12dB (12dB/octave low-shelf) ---
    m = _LS_12DB_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="LS", frequency_hz=freq, gain_db=gain, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- HS 12dB (12dB/octave high-shelf) ---
    m = _HS_12DB_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="HS", frequency_hz=freq, gain_db=gain, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- HP Butterworth (no Q specified) ---
    m = _HP_BW_RE.match(body)
    if m:
        freq = float(m.group(1))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="HP", frequency_hz=freq, gain_db=0.0, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- LP Butterworth (no Q specified) ---
    m = _LP_BW_RE.match(body)
    if m:
        freq = float(m.group(1))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="LP", frequency_hz=freq, gain_db=0.0, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- LS fixed slope (no Q specified) ---
    m = _LS_FIXED_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="LS", frequency_hz=freq, gain_db=gain, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- HS fixed slope (no Q specified) ---
    m = _HS_FIXED_RE.match(body)
    if m:
        freq = float(m.group(1))
        gain = float(m.group(2))
        _validate_frequency(freq, line_number=line_number)
        return (
            CanonicalFilter(
                type="HS", frequency_hz=freq, gain_db=gain, q=_BUTTERWORTH_Q
            ),
            None,
        )

    # --- Legacy full format: <type> Fc <freq> Hz Gain <gain> dB Q <q> ---
    # This catches LP/HS/LS/HP with Gain+Q in the format generated by REWGenerator
    m = _LEGACY_FULL_RE.match(body)
    if m:
        type_token = m.group(1)
        freq = float(m.group(2))
        gain = float(m.group(3))
        q = float(m.group(4))

        if type_token not in _TYPE_MAP:
            # Unknown type in legacy format — could be unsupported
            warning = ValidationWarning(
                field="filter_type",
                message=(
                    f"Unsupported filter type '{type_token}' at line {line_number}, skipping"
                ),
                original_value=type_token,
                clamped_value=None,
            )
            return (None, warning)

        _validate_frequency(freq, line_number=line_number)
        canonical_type = _TYPE_MAP[type_token]
        return (
            CanonicalFilter(
                type=canonical_type,  # type: ignore[arg-type]
                frequency_hz=freq,
                gain_db=gain,
                q=q,
            ),
            None,
        )

    # If we get here, the body didn't match any known pattern
    raise ParseError(
        f"Malformed filter line: '{body}'",
        line_number=line_number,
    )


class REWParser:
    """Parses REW EQ text files and REW HTTP API FilterSetting objects into CanonicalFilters."""

    def parse_file(self, path: Path) -> list[CanonicalFilter]:
        """Parse a REW EQ text file.

        Handles both the simple format (first line 'Equaliser: Parametric EQ')
        and the full REW "Filter Settings file" export format with preamble.

        Raises ParseError on malformed lines (with line number in message).
        Raises ValidationError for out-of-range frequency.
        Emits ValidationWarning for unsupported filter types (skips those bands).

        Returns:
            Tuple-like: list of CanonicalFilter objects. Access warnings via
            parse_file_with_warnings() for the full result.
        """
        result, _warnings = self.parse_file_with_warnings(path)
        return result

    def parse_file_with_warnings(
        self, path: Path
    ) -> tuple[list[CanonicalFilter], list[ValidationWarning]]:
        """Parse a REW EQ text file, returning both filters and warnings.

        Raises ParseError on malformed lines (with line number in message).
        Raises ValidationError for out-of-range frequency.

        Returns:
            Tuple of (filters, warnings).
        """
        text = path.read_text(encoding="utf-8")
        lines = text.splitlines()

        if not lines:
            raise ParseError(
                "Expected 'Equaliser:' header line but file is empty",
                line_number=1,
            )

        # Find the Equaliser: header line (skip preamble)
        equaliser_line_idx: int | None = None
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith("Equaliser:"):
                equaliser_line_idx = i
                break

        if equaliser_line_idx is None:
            raise ParseError(
                "Expected 'Equaliser:' header line not found in file",
                line_number=1,
            )

        # Parse filter lines after the equaliser header
        filters: list[CanonicalFilter] = []
        warnings: list[ValidationWarning] = []
        seen_filter_numbers: set[int] = set()

        for line_idx in range(equaliser_line_idx + 1, len(lines)):
            line = lines[line_idx]
            stripped = line.strip()
            line_number = line_idx + 1  # 1-based for error messages

            if not stripped:
                continue  # Skip blank lines

            # Try to match a filter line
            prefix_match = _FILTER_PREFIX_RE.match(stripped)
            if prefix_match is None:
                # Non-filter lines after the header (e.g. "L+R+Sub (closed)",
                # "No measurement") are silently skipped
                continue

            filter_num = int(prefix_match.group(1))
            state = prefix_match.group(2)  # ON or OFF
            body = prefix_match.group(3).strip()

            # Detect duplicate filter section (REW appends extra measurement filters)
            if filter_num in seen_filter_numbers:
                break  # Stop parsing — duplicate section starts here
            seen_filter_numbers.add(filter_num)

            # Parse the filter body
            result, warning = _parse_filter_body(body, line_number=line_number)

            if warning is not None:
                warnings.append(warning)
                continue  # Skip unsupported filter types

            if result is None:  # pragma: no cover
                continue

            # Apply OFF state: if state is OFF, override the type to OFF
            if state == "OFF":
                result = CanonicalFilter(
                    type="OFF",
                    frequency_hz=result.frequency_hz,
                    gain_db=result.gain_db,
                    q=result.q,
                )

            filters.append(result)

        return (filters, warnings)

    def parse_filter_settings(
        self, filter_settings: list[dict[str, object]]
    ) -> list[CanonicalFilter]:
        """Parse REW HTTP API FilterSetting objects into CanonicalFilters.

        Each FilterSetting has: enabled (bool), type (str), frequency (float),
        gain (float), q (float).

        Same validation rules as parse_file.
        """
        filters: list[CanonicalFilter] = []

        for i, setting in enumerate(filter_settings):
            enabled = setting.get("enabled", setting.get("on", True))
            type_token = str(setting.get("type", ""))
            freq = float(setting.get("frequency", setting.get("freq", 0.0)))  # type: ignore[arg-type]
            gain = float(setting.get("gain", 0.0))  # type: ignore[arg-type]
            q = float(setting.get("q", 1.0))  # type: ignore[arg-type]

            # Validate type token
            if type_token not in _API_TYPE_MAP:
                raise ValidationError(
                    f"Filter {i + 1}: Unknown filter type '{type_token}'"
                )

            # Validate frequency
            if not (10.0 <= freq <= 22000.0):
                raise ValidationError(
                    f"Filter {i + 1}: Frequency {freq} Hz is outside valid range 10-22000 Hz"
                )

            # Determine canonical type
            if not enabled:
                canonical_type = "OFF"
            else:
                canonical_type = _API_TYPE_MAP[type_token]

            filters.append(
                CanonicalFilter(
                    type=canonical_type,  # type: ignore[arg-type]
                    frequency_hz=freq,
                    gain_db=gain,
                    q=q,
                )
            )

        return filters
