"""Single source of truth for the application version string."""

from __future__ import annotations

import importlib.metadata

_FALLBACK_VERSION = "0.0.0-dev"


def get_app_version() -> str:
    """Return the application's version string.

    Resolution order:
      1. ``src._version.__version__`` — generated by setuptools_scm from the
         git tag at build/install time. This is a plain bundled module, so it
         resolves correctly inside a frozen PyInstaller binary, unlike
         ``importlib.metadata`` lookups which rely on installed package
         metadata that frozen apps don't carry.
      2. ``importlib.metadata.version("wiim-rew-sync")`` — covers editable/
         dev installs where the generated file may be stale or absent.
      3. A hardcoded fallback, for a source checkout with neither.
    """
    try:
        from src._version import __version__

        return __version__
    except ImportError:
        pass

    try:
        return importlib.metadata.version("wiim-rew-sync")
    except importlib.metadata.PackageNotFoundError:
        return _FALLBACK_VERSION
